/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TransacoesRouteImport } from './routes/transacoes'
import { Route as NovaDividaRouteImport } from './routes/nova-divida'
import { Route as MinhasDividasRouteImport } from './routes/minhas-dividas'
import { Route as CarteiraRouteImport } from './routes/carteira'
import { Route as IndexRouteImport } from './routes/index'

const TransacoesRoute = TransacoesRouteImport.update({
  id: '/transacoes',
  path: '/transacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const NovaDividaRoute = NovaDividaRouteImport.update({
  id: '/nova-divida',
  path: '/nova-divida',
  getParentRoute: () => rootRouteImport,
} as any)
const MinhasDividasRoute = MinhasDividasRouteImport.update({
  id: '/minhas-dividas',
  path: '/minhas-dividas',
  getParentRoute: () => rootRouteImport,
} as any)
const CarteiraRoute = CarteiraRouteImport.update({
  id: '/carteira',
  path: '/carteira',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/carteira': typeof CarteiraRoute
  '/minhas-dividas': typeof MinhasDividasRoute
  '/nova-divida': typeof NovaDividaRoute
  '/transacoes': typeof TransacoesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/carteira': typeof CarteiraRoute
  '/minhas-dividas': typeof MinhasDividasRoute
  '/nova-divida': typeof NovaDividaRoute
  '/transacoes': typeof TransacoesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/carteira': typeof CarteiraRoute
  '/minhas-dividas': typeof MinhasDividasRoute
  '/nova-divida': typeof NovaDividaRoute
  '/transacoes': typeof TransacoesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/carteira'
    | '/minhas-dividas'
    | '/nova-divida'
    | '/transacoes'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/carteira' | '/minhas-dividas' | '/nova-divida' | '/transacoes'
  id:
    | '__root__'
    | '/'
    | '/carteira'
    | '/minhas-dividas'
    | '/nova-divida'
    | '/transacoes'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CarteiraRoute: typeof CarteiraRoute
  MinhasDividasRoute: typeof MinhasDividasRoute
  NovaDividaRoute: typeof NovaDividaRoute
  TransacoesRoute: typeof TransacoesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/transacoes': {
      id: '/transacoes'
      path: '/transacoes'
      fullPath: '/transacoes'
      preLoaderRoute: typeof TransacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nova-divida': {
      id: '/nova-divida'
      path: '/nova-divida'
      fullPath: '/nova-divida'
      preLoaderRoute: typeof NovaDividaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/minhas-dividas': {
      id: '/minhas-dividas'
      path: '/minhas-dividas'
      fullPath: '/minhas-dividas'
      preLoaderRoute: typeof MinhasDividasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carteira': {
      id: '/carteira'
      path: '/carteira'
      fullPath: '/carteira'
      preLoaderRoute: typeof CarteiraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CarteiraRoute: CarteiraRoute,
  MinhasDividasRoute: MinhasDividasRoute,
  NovaDividaRoute: NovaDividaRoute,
  TransacoesRoute: TransacoesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
