/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as NovaDividaRouteImport } from './routes/nova-divida'
import { Route as MinhasDividasRouteImport } from './routes/minhas-dividas'
import { Route as IndexRouteImport } from './routes/index'

const NovaDividaRoute = NovaDividaRouteImport.update({
  id: '/nova-divida',
  path: '/nova-divida',
  getParentRoute: () => rootRouteImport,
} as any)
const MinhasDividasRoute = MinhasDividasRouteImport.update({
  id: '/minhas-dividas',
  path: '/minhas-dividas',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/minhas-dividas': typeof MinhasDividasRoute
  '/nova-divida': typeof NovaDividaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/minhas-dividas': typeof MinhasDividasRoute
  '/nova-divida': typeof NovaDividaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/minhas-dividas': typeof MinhasDividasRoute
  '/nova-divida': typeof NovaDividaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/minhas-dividas' | '/nova-divida'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/minhas-dividas' | '/nova-divida'
  id: '__root__' | '/' | '/minhas-dividas' | '/nova-divida'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MinhasDividasRoute: typeof MinhasDividasRoute
  NovaDividaRoute: typeof NovaDividaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/nova-divida': {
      id: '/nova-divida'
      path: '/nova-divida'
      fullPath: '/nova-divida'
      preLoaderRoute: typeof NovaDividaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/minhas-dividas': {
      id: '/minhas-dividas'
      path: '/minhas-dividas'
      fullPath: '/minhas-dividas'
      preLoaderRoute: typeof MinhasDividasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MinhasDividasRoute: MinhasDividasRoute,
  NovaDividaRoute: NovaDividaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
